# Generated by Django 4.2.7 on 2024-01-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='date',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='image',
        ),
    ]
